version: 0.2

phases:
  install:
    commands:
      - echo "Installing AWS CLI !!!..."

  pre_build:
    commands:
      - echo "Creating User and Group!!!"

  build:
    commands:
      - echo "Creating a new IAM User..."
      - aws iam create-user --user-name Sakshi

      - echo "Creating a new IAM Group..."
      - aws iam create-group --group-name devops

      - echo "Assign full access to s3 bucket..."
      - aws iam attach-group-policy --group-name devops --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess
      
      - echo "Creating a new s3 bucket..."
      - aws s3api create-bucket --bucket 002oct-awsdevops --region us-east-1

  post_build:
    commands:
      - echo "Deleting the IAM User..."
      - aws iam delete-user --user-name Sakshi
      - echo "User deleted successfully..._."

artifacts:
  files:
    - "**/*" # Include any output files if necessary
